name: scrollable_clean_calendar
description: A clean calendar widget with vertical scroll, locale, and range selection date
version: 1.4.0
homepage: https://github.com/FabioFiuza/scrollable_clean_calendar

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.7.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  scrollable_positioned_list: 0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
